### ISSUE TITLE
Error: too few values to unpack

### ISSUE THREAD

**Issue by Sebelino** [bookingcom/rules_lombok_java_library#1]
Hi, I cloned the repository and I am encountering a build error:
```
$ bazel run //example/src/main/java/com/example:runner

ERROR: Traceback (most recent call last):
	File "/home/sebelino/src/rules_lombok_java_library/example/src/main/java/com/example/cmdline/BUILD", line 4, column 20, in <toplevel>
		lombok_java_library(
	File "/home/sebelino/src/rules_lombok_java_library/rules.bzl", line 11, column 25, in lombok_java_library
		path, file_name = src.rsplit("/", 1)
Error: too few values to unpack (got 1, want 2)
ERROR: /home/sebelino/src/rules_lombok_java_library/example/src/main/java/com/example/BUILD:3:13: no such target '//example/src/main/java/com/example/cmdline:lombok_example': target 'lombok_example' not declared in package 'example/src/main/java/com/example/cmdline' defined by /home/sebelino/src/rules_lombok_java_library/example/src/main/java/com/example/cmdline/BUILD and referenced by '//example/src/main/java/com/example:lombok_external_user_example'
ERROR: Analysis of target '//example/src/main/java/com/example:runner' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.123s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 23 targets configured)
FAILED: Build did NOT complete successfully (2 packages loaded, 23 targets configured)
    currently loading: @bazel_tools//src/tools/launcher ... (2 packages)
```

```
$ git rev-parse HEAD           
0ab9856814fc950070d08e523ccd32bcca67fcc7

$ bazel version                                       
Build label: 4.1.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jan 1 00:00:00 1980 (315532800)
Build timestamp: 315532800
Build timestamp as int: 315532800
```

**Comment by Sebelino** [comment]
Looks like `src` won't contain any slashes, so unpacking it into two parts fails.
```
DEBUG: rules.bzl:10:10: srcs = ["LombokExample.java"]
```

**Comment by manuelnaranjo** [comment]
@Sebelino we're using this rules internally, we figured out that it would mess with IDE integration (looking at you intellij) so we  ended up adding the flag `--nojava_header_compilation` to disable turbine as we couldn't manage to look closer into this topic.

But I wouldn't mind applying fixes if you have them
